### PR TITLE
Format README.md

### PR DESCRIPTION
**Pull request by tbeseda**
Hi Jay! I enjoyed learning about Citizen recently. 9+ years in the making; nice job!

In this PR I've formatted code blocks in the README to enable syntax highlighting in the rendered GitHub Markdown.  
I don't think this is necessary, but it does help me parse the docs as I learn about Citizen.

(btw it was kinda nice to not have to page through a flashy marketing site 😎)

### CODE REVIEW

**Comment by tbeseda** [comment]
It may be helpful to review [the rendered output here](https://github.com/jaysylvester/citizen/blob/f38d5e378de5db9786400a8683e39ddd4b871dcd/README.md)

**Comment by jaysylvester** [comment]
Thanks Taylor! #132 proposes similar changes, so I need to compare them.

**Comment by tbeseda** [comment]
> #132 proposes similar changes

Ah, dang! I shoulda checked first 🙃 Sorry @Meantub, I could have assisted on yours.

Anyway, looks like the main difference is that this PR un-indents the code blocks as well as adding fences. Which is why my diff is huge.

**Comment by Meantub** [comment]
All good, either one does something similar, took me like 15 mins max

**Comment by jaysylvester** [comment]
I went with this one since it removed the (now) unnecessary indentations. Thanks to both of you though for your contributions!

**Pull request merged**
